In [1]:
print('i am excited about pytorch')

i am excited about pytorch


In [2]:
!nvidia-smi

Sun Jul 16 15:12:33 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   47C    P0              14W /  40W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.0.1+cu117


# introduction to tensors

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [19]:
torch.rand(3,3)

tensor([[0.1849, 0.5488, 0.9816],
        [0.9952, 0.0697, 0.5605],
        [0.2400, 0.5214, 0.6656]])

In [20]:
random_tensor_a=torch.rand(3,4)
random_tensor_b=torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[7.1505e-02, 9.5194e-01, 7.3576e-04, 1.4932e-01],
        [2.9555e-01, 7.9309e-01, 4.2899e-01, 3.4681e-01],
        [8.9127e-01, 3.0095e-02, 1.5092e-01, 5.2866e-01]])
tensor([[0.8461, 0.6565, 0.6540, 0.1866],
        [0.4982, 0.4519, 0.2897, 0.4413],
        [0.0324, 0.5832, 0.6683, 0.9116]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [22]:
1==1

True

In [24]:
RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d=torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [25]:
torch.cuda.is_available()

True

In [27]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'